name: fp-collapse-monitor
summary: Simple out-of-the-box browser for collapse maps worldwide.
description: |
      Simple out-of-the-box browser for collapse maps worldwide.
version: git
grade: stable
confinement: strict
base: core20
architectures:
  - build-on: [amd64]

apps:
  fp-collapse-monitor:
    command: bin/fp-collapse-monitor
    extensions: [gnome-3-38]
    plugs:
        - home
        - network
        - x11
        - desktop
        - desktop-legacy
        - gsettings
        gnome-3-38-2004:
          default-provider: gnome-3-38-2004
          interface: content
          target: $SNAP/gnome-platform
        gtk-3-themes:
          default-provider: gtk-common-themes
          interface: content
          target: $SNAP/data-dir/themes
        icon-themes:
          default-provider: gtk-common-themes
          interface: content
          target: $SNAP/data-dir/icons
        sound-themes:
          default-provider: gtk-common-themes
          interface: content
          target: $SNAP/data-dir/sounds
    environment:
      PYTHONPATH: $SNAP/usr/lib/python3/site-packages:$SNAP/usr/lib/python3/dist-packages:$PYTHONPATH
      GI_TYPELIB_PATH: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/girepository-1.0/
      GDK_PIXBUF_MODULE_FILE: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/gdk-pixbuf-2.0/loaders.cache
      
parts:
  fp-collapse-monitor:
    plugin: python
    source: https://github.com/fosspost/fp-collapse-monitor.git
    build-environment:
      - PYTHONUSERBASE: $SNAP_DATA/
    build-packages: [python3-pkg-resources]
    stage-packages: [python3-gi, gir1.2-webkit2-4.0, libgdk-pixbuf2.0-0, libpng16-16]
    
  dump-files:
    plugin: dump
    source: .
    organize:
      ui.glade: usr/share/fp-collapse-monitor/
      fp-collapse-monitor.png: usr/share/pixmaps/
      fp-collapse-monitor.desktop: usr/share/applications/
    
layout:
  /usr/share/fp-collapse-monitor:
    bind: $SNAP/usr/share/fp-collapse-monitor
  /usr/share/applications:
    bind: $SNAP/usr/share/applications
  /usr/share/pixmaps:
    bind: $SNAP/usr/share/pixmaps
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/webkit2gtk-4.0:
    bind: $SNAP/gnome-platform/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/webkit2gtk-4.0
  /usr/share/xml/iso-codes:
    bind: $SNAP/gnome-platform/usr/share/xml/iso-codes
